<% final String ct = "country"; %>

<div class="div-label"><label for="country"><%= langBundle.getString(ct + ".country") %></label><span class="required"></span></div>
<select id="country" name="country" required>
    <option value="af"><%= langBundle.getString(ct + ".af") %></option>
    <option value="al"><%= langBundle.getString(ct + ".al") %></option>
    <option value="dz"><%= langBundle.getString(ct + ".dz") %></option>
    <option value="ad"><%= langBundle.getString(ct + ".ad") %></option>
    <option value="ao"><%= langBundle.getString(ct + ".ao") %></option>
    <option value="ag"><%= langBundle.getString(ct + ".ag") %></option>
    <option value="ar"><%= langBundle.getString(ct + ".ar") %></option>
    <option value="am"><%= langBundle.getString(ct + ".am") %></option>
    <option value="au"><%= langBundle.getString(ct + ".au") %></option>
    <option value="at"><%= langBundle.getString(ct + ".at") %></option>
    <option value="az"><%= langBundle.getString(ct + ".az") %></option>
    <option value="bs"><%= langBundle.getString(ct + ".bs") %></option>
    <option value="bh"><%= langBundle.getString(ct + ".bh") %></option>
    <option value="bd"><%= langBundle.getString(ct + ".bd") %></option>
    <option value="bb"><%= langBundle.getString(ct + ".bb") %></option>
    <option value="by"><%= langBundle.getString(ct + ".by") %></option>
    <option value="be"><%= langBundle.getString(ct + ".be") %></option>
    <option value="bz"><%= langBundle.getString(ct + ".bz") %></option>
    <option value="bj"><%= langBundle.getString(ct + ".bj") %></option>
    <option value="bt"><%= langBundle.getString(ct + ".bt") %></option>
    <option value="bo"><%= langBundle.getString(ct + ".bo") %></option>
    <option value="ba"><%= langBundle.getString(ct + ".ba") %></option>
    <option value="bw"><%= langBundle.getString(ct + ".bw") %></option>
    <option value="br"><%= langBundle.getString(ct + ".br") %></option>
    <option value="bn"><%= langBundle.getString(ct + ".bn") %></option>
    <option value="bg"><%= langBundle.getString(ct + ".bg") %></option>
    <option value="bf"><%= langBundle.getString(ct + ".bf") %></option>
    <option value="bi"><%= langBundle.getString(ct + ".bi") %></option>
    <option value="kh"><%= langBundle.getString(ct + ".kh") %></option>
    <option value="cm"><%= langBundle.getString(ct + ".cm") %></option>
    <option value="ca"><%= langBundle.getString(ct + ".ca") %></option>
    <option value="cv"><%= langBundle.getString(ct + ".cv") %></option>
    <option value="cf"><%= langBundle.getString(ct + ".cf") %></option>
    <option value="td"><%= langBundle.getString(ct + ".td") %></option>
    <option value="cl"><%= langBundle.getString(ct + ".cl") %></option>
    <option value="cn"><%= langBundle.getString(ct + ".cn") %></option>
    <option value="co"><%= langBundle.getString(ct + ".co") %></option>
    <option value="km"><%= langBundle.getString(ct + ".km") %></option>
    <option value="cg"><%= langBundle.getString(ct + ".cg") %></option>
    <option value="cd"><%= langBundle.getString(ct + ".cd") %></option>
    <option value="cr"><%= langBundle.getString(ct + ".cr") %></option>
    <option value="ci"><%= langBundle.getString(ct + ".ci") %></option>
    <option value="hr"><%= langBundle.getString(ct + ".hr") %></option>
    <option value="cu"><%= langBundle.getString(ct + ".cu") %></option>
    <option value="cy"><%= langBundle.getString(ct + ".cy") %></option>
    <option value="cz"><%= langBundle.getString(ct + ".cz") %></option>
    <option value="dk"><%= langBundle.getString(ct + ".dk") %></option>
    <option value="dj"><%= langBundle.getString(ct + ".dj") %></option>
    <option value="dm"><%= langBundle.getString(ct + ".dm") %></option>
    <option value="do"><%= langBundle.getString(ct + ".do") %></option>
    <option value="ec"><%= langBundle.getString(ct + ".ec") %></option>
    <option value="eg"><%= langBundle.getString(ct + ".eg") %></option>
    <option value="sv"><%= langBundle.getString(ct + ".sv") %></option>
    <option value="gq"><%= langBundle.getString(ct + ".gq") %></option>
    <option value="er"><%= langBundle.getString(ct + ".er") %></option>
    <option value="ee"><%= langBundle.getString(ct + ".ee") %></option>
    <option value="sz"><%= langBundle.getString(ct + ".sz") %></option>
    <option value="et"><%= langBundle.getString(ct + ".et") %></option>
    <option value="fj"><%= langBundle.getString(ct + ".fj") %></option>
    <option value="fi"><%= langBundle.getString(ct + ".fi") %></option>
    <option value="fr"><%= langBundle.getString(ct + ".fr") %></option>
    <option value="ga"><%= langBundle.getString(ct + ".ga") %></option>
    <option value="gm"><%= langBundle.getString(ct + ".gm") %></option>
    <option value="ge"><%= langBundle.getString(ct + ".ge") %></option>
    <option value="de"><%= langBundle.getString(ct + ".de") %></option>
    <option value="gh"><%= langBundle.getString(ct + ".gh") %></option>
    <option value="gr"><%= langBundle.getString(ct + ".gr") %></option>
    <option value="gd"><%= langBundle.getString(ct + ".gd") %></option>
    <option value="gt"><%= langBundle.getString(ct + ".gt") %></option>
    <option value="gn"><%= langBundle.getString(ct + ".gn") %></option>
    <option value="gw"><%= langBundle.getString(ct + ".gw") %></option>
    <option value="gy"><%= langBundle.getString(ct + ".gy") %></option>
    <option value="ht"><%= langBundle.getString(ct + ".ht") %></option>
    <option value="hn"><%= langBundle.getString(ct + ".hn") %></option>
    <option value="hu"><%= langBundle.getString(ct + ".hu") %></option>
    <option value="is"><%= langBundle.getString(ct + ".is") %></option>
    <option value="in"><%= langBundle.getString(ct + ".in") %></option>
    <option value="id"><%= langBundle.getString(ct + ".id") %></option>
    <option value="ir"><%= langBundle.getString(ct + ".ir") %></option>
    <option value="iq"><%= langBundle.getString(ct + ".iq") %></option>
    <option value="ie"><%= langBundle.getString(ct + ".ie") %></option>
    <option value="il"><%= langBundle.getString(ct + ".il") %></option>
    <option value="it"><%= langBundle.getString(ct + ".it") %></option>
    <option value="jm"><%= langBundle.getString(ct + ".jm") %></option>
    <option value="jp"><%= langBundle.getString(ct + ".jp") %></option>
    <option value="jo"><%= langBundle.getString(ct + ".jo") %></option>
    <option value="kz"><%= langBundle.getString(ct + ".kz") %></option>
    <option value="ke"><%= langBundle.getString(ct + ".ke") %></option>
    <option value="ki"><%= langBundle.getString(ct + ".ki") %></option>
    <option value="kw"><%= langBundle.getString(ct + ".kw") %></option>
    <option value="kg"><%= langBundle.getString(ct + ".kg") %></option>
    <option value="la"><%= langBundle.getString(ct + ".la") %></option>
    <option value="lv"><%= langBundle.getString(ct + ".lv") %></option>
    <option value="lb"><%= langBundle.getString(ct + ".lb") %></option>
    <option value="ls"><%= langBundle.getString(ct + ".ls") %></option>
    <option value="lr"><%= langBundle.getString(ct + ".lr") %></option>
    <option value="ly"><%= langBundle.getString(ct + ".ly") %></option>
    <option value="li"><%= langBundle.getString(ct + ".li") %></option>
    <option value="lt"><%= langBundle.getString(ct + ".lt") %></option>
    <option value="lu"><%= langBundle.getString(ct + ".lu") %></option>
    <option value="mg"><%= langBundle.getString(ct + ".mg") %></option>
    <option value="mw"><%= langBundle.getString(ct + ".mw") %></option>
    <option value="my"><%= langBundle.getString(ct + ".my") %></option>
    <option value="mv"><%= langBundle.getString(ct + ".mv") %></option>
    <option value="ml"><%= langBundle.getString(ct + ".ml") %></option>
    <option value="mt"><%= langBundle.getString(ct + ".mt") %></option>
    <option value="mh"><%= langBundle.getString(ct + ".mh") %></option>
    <option value="mr"><%= langBundle.getString(ct + ".mr") %></option>
    <option value="mu"><%= langBundle.getString(ct + ".mu") %></option>
    <option value="mx"><%= langBundle.getString(ct + ".mx") %></option>
    <option value="fm"><%= langBundle.getString(ct + ".fm") %></option>
    <option value="md"><%= langBundle.getString(ct + ".md") %></option>
    <option value="mc"><%= langBundle.getString(ct + ".mc") %></option>
    <option value="mn"><%= langBundle.getString(ct + ".mn") %></option>
    <option value="me"><%= langBundle.getString(ct + ".me") %></option>
    <option value="ma"><%= langBundle.getString(ct + ".ma") %></option>
    <option value="mz"><%= langBundle.getString(ct + ".mz") %></option>
    <option value="mm"><%= langBundle.getString(ct + ".mm") %></option>
    <option value="na"><%= langBundle.getString(ct + ".na") %></option>
    <option value="nr"><%= langBundle.getString(ct + ".nr") %></option>
    <option value="np"><%= langBundle.getString(ct + ".np") %></option>
    <option value="nl"><%= langBundle.getString(ct + ".nl") %></option>
    <option value="nz"><%= langBundle.getString(ct + ".nz") %></option>
    <option value="ni"><%= langBundle.getString(ct + ".ni") %></option>
    <option value="ne"><%= langBundle.getString(ct + ".ne") %></option>
    <option value="ng"><%= langBundle.getString(ct + ".ng") %></option>
    <option value="kp"><%= langBundle.getString(ct + ".kp") %></option>
    <option value="mk"><%= langBundle.getString(ct + ".mk") %></option>
    <option value="no"><%= langBundle.getString(ct + ".no") %></option>
    <option value="om"><%= langBundle.getString(ct + ".om") %></option>
    <option value="pk"><%= langBundle.getString(ct + ".pk") %></option>
    <option value="pw"><%= langBundle.getString(ct + ".pw") %></option>
    <option value="pa"><%= langBundle.getString(ct + ".pa") %></option>
    <option value="pg"><%= langBundle.getString(ct + ".pg") %></option>
    <option value="py"><%= langBundle.getString(ct + ".py") %></option>
    <option value="pe"><%= langBundle.getString(ct + ".pe") %></option>
    <option value="ph"><%= langBundle.getString(ct + ".ph") %></option>
    <option value="pl"><%= langBundle.getString(ct + ".pl") %></option>
    <option value="pt"><%= langBundle.getString(ct + ".pt") %></option>
    <option value="qa"><%= langBundle.getString(ct + ".qa") %></option>
    <option value="ro"><%= langBundle.getString(ct + ".ro") %></option>
    <option value="ru"><%= langBundle.getString(ct + ".ru") %></option>
    <option value="rw"><%= langBundle.getString(ct + ".rw") %></option>
    <option value="ws"><%= langBundle.getString(ct + ".ws") %></option>
    <option value="sm"><%= langBundle.getString(ct + ".sm") %></option>
    <option value="sa"><%= langBundle.getString(ct + ".sa") %></option>
    <option value="sn"><%= langBundle.getString(ct + ".sn") %></option>
    <option value="rs"><%= langBundle.getString(ct + ".rs") %></option>
    <option value="sc"><%= langBundle.getString(ct + ".sc") %></option>
    <option value="sl"><%= langBundle.getString(ct + ".sl") %></option>
    <option value="sg"><%= langBundle.getString(ct + ".sg") %></option>
    <option value="sk"><%= langBundle.getString(ct + ".sk") %></option>
    <option value="si"><%= langBundle.getString(ct + ".si") %></option>
    <option value="sb"><%= langBundle.getString(ct + ".sb") %></option>
    <option value="so"><%= langBundle.getString(ct + ".so") %></option>
    <option value="za"><%= langBundle.getString(ct + ".za") %></option>
    <option value="kr"><%= langBundle.getString(ct + ".kr") %></option>
    <option value="ss"><%= langBundle.getString(ct + ".ss") %></option>
    <option value="es"><%= langBundle.getString(ct + ".es") %></option>
    <option value="lk"><%= langBundle.getString(ct + ".lk") %></option>
    <option value="kn"><%= langBundle.getString(ct + ".kn") %></option>
    <option value="lc"><%= langBundle.getString(ct + ".lc") %></option>
    <option value="vc"><%= langBundle.getString(ct + ".vc") %></option>
    <option value="sd"><%= langBundle.getString(ct + ".sd") %></option>
    <option value="sr"><%= langBundle.getString(ct + ".sr") %></option>
    <option value="se"><%= langBundle.getString(ct + ".se") %></option>
    <option value="ch"><%= langBundle.getString(ct + ".ch") %></option>
    <option value="sy"><%= langBundle.getString(ct + ".sy") %></option>
    <option value="st"><%= langBundle.getString(ct + ".st") %></option>
    <option value="tw"><%= langBundle.getString(ct + ".tw") %></option>
    <option value="tj"><%= langBundle.getString(ct + ".tj") %></option>
    <option value="tz"><%= langBundle.getString(ct + ".tz") %></option>
    <option value="th"><%= langBundle.getString(ct + ".th") %></option>
    <option value="tl"><%= langBundle.getString(ct + ".tl") %></option>
    <option value="tg"><%= langBundle.getString(ct + ".tg") %></option>
    <option value="to"><%= langBundle.getString(ct + ".to") %></option>
    <option value="tt"><%= langBundle.getString(ct + ".tt") %></option>
    <option value="tn"><%= langBundle.getString(ct + ".tn") %></option>
    <option value="tm"><%= langBundle.getString(ct + ".tm") %></option>
    <option value="tv"><%= langBundle.getString(ct + ".tv") %></option>
    <option value="tr"><%= langBundle.getString(ct + ".tr") %></option>
    <option value="ug"><%= langBundle.getString(ct + ".ug") %></option>
    <option value="ua"><%= langBundle.getString(ct + ".ua") %></option>
    <option value="ae"><%= langBundle.getString(ct + ".ae") %></option>
    <option value="gb"><%= langBundle.getString(ct + ".gb") %></option>
    <option value="us"><%= langBundle.getString(ct + ".us") %></option>
    <option value="uy"><%= langBundle.getString(ct + ".uy") %></option>
    <option value="uz"><%= langBundle.getString(ct + ".uz") %></option>
    <option value="vu"><%= langBundle.getString(ct + ".vu") %></option>
    <option value="va"><%= langBundle.getString(ct + ".va") %></option>
    <option value="ve"><%= langBundle.getString(ct + ".ve") %></option>
    <option value="vn"><%= langBundle.getString(ct + ".vn") %></option>
    <option value="ye"><%= langBundle.getString(ct + ".ye") %></option>
    <option value="zm"><%= langBundle.getString(ct + ".zm") %></option>
    <option value="zw"><%= langBundle.getString(ct + ".zw") %></option>
</select>